var Kalendae = {
    "util": {
        "isIE8": function () {},
        "$": function () {},
        "$$": function () {},
        "make": function () {},
        "isVisible": function () {},
        "getStyle": function () {},
        "domReady": function () {},
        "addEvent": function () {},
        "removeEvent": function () {},
        "fireEvent": function () {},
        "hasClassName": function () {},
        "addClassName": function () {},
        "removeClassName": function () {},
        "isFixed": function () {},
        "scrollContainer": function () {},
        "getPosition": function () {},
        "getHeight": function () {},
        "getWidth": function () {},
        "trimString": function () {},
        "merge": function () {},
        "isArray": function () {}
    },
    "Input": function () {},
    "moment": {
        "utc": function () {},
        "unix": function () {},
        "duration": {
            "fn": {
                "_bubble": function () {},
                "weeks": function () {},
                "valueOf": function () {},
                "humanize": function () {},
                "add": function () {},
                "subtract": function () {},
                "get": function () {},
                "as": function () {},
                "lang": function () {},
                "asMilliseconds": function () {},
                "milliseconds": function () {},
                "asSeconds": function () {},
                "seconds": function () {},
                "asMinutes": function () {},
                "minutes": function () {},
                "asHours": function () {},
                "hours": function () {},
                "asDays": function () {},
                "days": function () {},
                "asMonths": function () {},
                "months": function () {},
                "asYears": function () {},
                "years": function () {},
                "asWeeks": function () {},
                "_lang": {
                    "ordinal": function () {},
                    "_abbr": {},
                    "set": function () {},
                    "_months": {},
                    "months": function () {},
                    "_monthsShort": {},
                    "monthsShort": function () {},
                    "monthsParse": function () {},
                    "_weekdays": {},
                    "weekdays": function () {},
                    "_weekdaysShort": {},
                    "weekdaysShort": function () {},
                    "_weekdaysMin": {},
                    "weekdaysMin": function () {},
                    "weekdaysParse": function () {},
                    "_longDateFormat": {
                        "LT": {},
                        "L": {},
                        "LL": {},
                        "LLL": {},
                        "LLLL": {}
                    },
                    "longDateFormat": function () {},
                    "isPM": function () {},
                    "_meridiemParse": {},
                    "meridiem": function () {},
                    "_calendar": {
                        "sameDay": {},
                        "nextDay": {},
                        "nextWeek": {},
                        "lastDay": {},
                        "lastWeek": {},
                        "sameElse": {}
                    },
                    "calendar": function () {},
                    "_relativeTime": {
                        "future": {},
                        "past": {},
                        "s": {},
                        "m": {},
                        "mm": {},
                        "h": {},
                        "hh": {},
                        "d": {},
                        "dd": {},
                        "M": {},
                        "MM": {},
                        "y": {},
                        "yy": {}
                    },
                    "relativeTime": function () {},
                    "pastFuture": function () {},
                    "_ordinal": {},
                    "preparse": function () {},
                    "postformat": function () {},
                    "week": function () {},
                    "_week": {
                        "dow": {},
                        "doy": {}
                    }
                }
            }
        },
        "version": {},
        "defaultFormat": {},
        "updateOffset": function () {},
        "lang": function () {},
        "langData": function () {},
        "isMoment": function () {},
        "isDuration": function () {},
        "fn": {
            "clone": function () {},
            "valueOf": function () {},
            "unix": function () {},
            "toString": function () {},
            "toDate": function () {},
            "toISOString": function () {},
            "toArray": function () {},
            "isValid": function () {},
            "utc": function () {},
            "local": function () {},
            "format": function () {},
            "add": function () {},
            "subtract": function () {},
            "diff": function () {},
            "from": function () {},
            "fromNow": function () {},
            "calendar": function () {},
            "isLeapYear": function () {},
            "isDST": function () {},
            "day": function () {},
            "month": function () {},
            "startOf": function () {},
            "endOf": function () {},
            "isAfter": function () {},
            "isBefore": function () {},
            "isSame": function () {},
            "min": function () {},
            "max": function () {},
            "zone": function () {},
            "zoneAbbr": function () {},
            "zoneName": function () {},
            "daysInMonth": function () {},
            "dayOfYear": function () {},
            "weekYear": function () {},
            "isoWeekYear": function () {},
            "week": function () {},
            "isoWeek": function () {},
            "weekday": function () {},
            "isoWeekday": function () {},
            "lang": function () {},
            "dates": function () {},
            "date": function () {},
            "hours": function () {},
            "hour": function () {},
            "minutes": function () {},
            "minute": function () {},
            "seconds": function () {},
            "second": function () {},
            "milliseconds": function () {},
            "millisecond": function () {},
            "years": function () {},
            "year": function () {},
            "days": function () {},
            "months": function () {},
            "weeks": function () {},
            "isoWeeks": function () {},
            "toJSON": function () {},
            "_lang": {
                "ordinal": function () {},
                "_abbr": {},
                "set": function () {},
                "_months": {},
                "months": function () {},
                "_monthsShort": {},
                "monthsShort": function () {},
                "monthsParse": function () {},
                "_weekdays": {},
                "weekdays": function () {},
                "_weekdaysShort": {},
                "weekdaysShort": function () {},
                "_weekdaysMin": {},
                "weekdaysMin": function () {},
                "weekdaysParse": function () {},
                "_longDateFormat": {
                    "LT": {},
                    "L": {},
                    "LL": {},
                    "LLL": {},
                    "LLLL": {}
                },
                "longDateFormat": function () {},
                "isPM": function () {},
                "_meridiemParse": {},
                "meridiem": function () {},
                "_calendar": {
                    "sameDay": {},
                    "nextDay": {},
                    "nextWeek": {},
                    "lastDay": {},
                    "lastWeek": {},
                    "sameElse": {}
                },
                "calendar": function () {},
                "_relativeTime": {
                    "future": {},
                    "past": {},
                    "s": {},
                    "m": {},
                    "mm": {},
                    "h": {},
                    "hh": {},
                    "d": {},
                    "dd": {},
                    "M": {},
                    "MM": {},
                    "y": {},
                    "yy": {}
                },
                "relativeTime": function () {},
                "pastFuture": function () {},
                "_ordinal": {},
                "preparse": function () {},
                "postformat": function () {},
                "week": function () {},
                "_week": {
                    "dow": {},
                    "doy": {}
                }
            },
            "yearDay": function () {}
        }
    }
};
Kalendae.prototype = {
    "defaults": function () {},
    "classes": function () {},
    "disablePreviousMonth": function () {},
    "disableNextMonth": function () {},
    "disablePreviousYear": function () {},
    "disableNextYear": function () {},
    "directions": function () {},
    "getSelectedAsDates": function () {},
    "getSelectedAsText": function () {},
    "getSelectedRaw": function () {},
    "getSelected": function () {},
    "isSelected": function () {},
    "setSelected": function () {},
    "addSelected": function () {},
    "weekSelected": function () {},
    "makeSelectedDateVisible": function () {},
    "removeSelected": function () {},
    "draw": function () {}
};
Kalendae.Input.prototype = {
    "defaults": function () {},
    "classes": function () {},
    "disablePreviousMonth": function () {},
    "disableNextMonth": function () {},
    "disablePreviousYear": function () {},
    "disableNextYear": function () {},
    "directions": function () {},
    "getSelectedAsDates": function () {},
    "getSelectedAsText": function () {},
    "getSelectedRaw": function () {},
    "getSelected": function () {},
    "isSelected": function () {},
    "setSelected": function () {},
    "addSelected": function () {},
    "weekSelected": function () {},
    "makeSelectedDateVisible": function () {},
    "removeSelected": function () {},
    "draw": function () {},
    "show": function () {},
    "hide": function () {},
    "destroy": function () {}
};
